### ISSUE TITLE
The auto sweep doesn`t toggle

### ISSUE THREAD

**Issue by Arroiz147** [houdini101/AHK_Minecraft_Tools#1]
HI, awesome project, thanks a lot.
I can toggle auto fishing and portal fine but the auto sweep just doesn`t toggle. I already tried to change the key to alt + b but neither worked.

**Comment by houdini101** [comment]
> HI, awesome project, thanks a lot.
> I can toggle auto fishing and portal fine but the auto sweep just doesn`t toggle. I already tried to change the key to alt + b but neither worked.

Hi, thanks for the compliment.
Regarding the Auto-Sweep, I tested the script and it worked just fine for me. Did it run the first time you activated it, and just continue auto-attacking and won't turn-off? Auto-Sweep only triggers when there's a sword icon below the crosshair. Also, I forgot to mention that the Auto-Sweep attack only works best when the cursor/crosshair is pointed on dark-colored mobs, otherwise it will continue to trigger when the crosshair is pointed on lighter colors (e.g. white wool, sand, etc.).

**Comment by hendikep** [comment]
Same here. Both of the other functions work normally but when I try and toggle auto sweep nothing happens.

**Comment by RaXorX** [comment]
Tried it too but to no avail, even on dark backgrounds like the grass or trees. As per you the script should just work everywhere regardless of what it is attacking. I might be wrong but it could be possible that the crosshair icon changed from what you have currently. 

I'll try with the new crosshair file and get back to you if it works.

**Comment by houdini101** [comment]
> Same here. Both of the other functions work normally but when I try and toggle auto sweep nothing happens.

Hi!
Before you used the Auto-Sweep, did you set the Attack Indicator in Minecraft Settings to Crosshair? If so, have you tried pointing the crosshair on mobs? Once you toggle the Auto-Sweep to ON, it will wait for the Sword Icon to appear under the Crosshair, before it sweeps once, then the process repeats.
Let me know if it still does not work, and I'll think of a better solution.

**Comment by houdini101** [comment]
> Tried it too but to no avail, even on dark backgrounds like the grass or trees. As per you the script should just work everywhere regardless of what it is attacking. I might be wrong but it could be possible that the crosshair icon changed from what you have currently.
> 
> I'll try with the new crosshair file and get back to you if it works.
> EDIT: Nope, even with the new crosshair it doesn't work.

Hi!
Before you used the Auto-Sweep, did you set the Attack Indicator in Minecraft Settings to Crosshair? If so, have you tried pointing the crosshair on mobs? Once you toggle the Auto-Sweep to ON, it will wait for the Sword Icon to appear under the Crosshair, before it sweeps once, then the process repeats.
Let me know if it still does not work, and I'll think of a better solution.

**Comment by houdini101** [comment]
@RaXorX 
> Sorry for the late reply, notifications from github are a pain. Anyways, you're right. It works albeit it's way too finicky. As you said it really only works on dark background. And I see now what it is searching for actually. That little cross under the sword icon.
> I think we need a better solution perhaps indeed.
> 
> EDIT: Okay, I think there are a couple things to note.
> 
> 1. Do we really need to search for the star icon (the plus icon below the sword) or anything at all?
>    :: Because as far as I can see this is most useful when and especially there's some sort of a grinder or similar farm available. Aka, since the player would be in the same position attacking in a limited area and not to mention for a continous period of time, so why not just spam the left mouse click instead of searching for it. You can still search and increase the variation from 90 to 200+ (I set it at 255 and it'd constantly keep spamming it)
>    I can see some reasons why there was a need to search for but maybe it might not be so necessary and you tried to curb that up. I was in a desert area over sand and it wasn't having any effects because there was no target at all. I think majority of us who had this issue had no target and simply wanted to test out the script perhaps. And you saying that it could keep spamming on light colored blocks like cotton etc etc I think that made it a little misunderstood since at least I thought it'll just start spamming the left mouse click.
> 2. I think if you still really want to go that route it can be done but with something extra. Basically, provide a mod to that changes the icon file, only changing that small plus icon with a semi dark background like the captions have. That way the icon will have a little dark background and white plus over it which will make it easier. I can make the mod if you want to but again, since the entire thing was going to be a continous thing it feels a bit far fetched. Let me hear your opinions on it.
> 3. I think what would be better instead would be this. I am actually in the process of modifying the script myself with some changes already. But the idea is to instead include a drop down button in the gui to indicate what your weapon is. A sword/axe/pickaxe/trident/hoe/bow/crossbow (yeah it could be made to include those too) and set the waiting interval accordingly. For an axe for example, in my tests a delay of about 1.2 seconds worked best. It could even be lower perhaps. In that delay it was able to recharge the sword fully to attack at full power again. In that way there's no need to search for the star icon and instead have a variable that changes according to your mode of weapon and simply changes the delay according to it. All one needs to do is a little research into the delay period for each weapon, nothing so hard. Or instead you could include a text area for one to fill out the exact amount of time to wait before spamming and include the times for each individual weapon in it.

Hi!, I'm glad that you finally figure out what the Auto-Sweep Attack is. It's my bad for not explaining it fully.

The reason behind using the + on the sword icon as the search image was because I was trying to use the full potential of the weapon's damage, dealing the max damage input using the sweep, and making the attack do an area damage. It also reduce the risk of destroying the weapon by over-using it on a single mob if I use the attack-spam method, since attacking without waiting for the sword icon to fill, will only damage a single mob.

With regards to the image search of the + icon, I only used it to decrease the value of the hbitmap, to easily locate the image without putting additional load on the cpu using the imagesearch. The smaller the size, the better. The Imagesearch uses the Transblack method, or Transparent Black, meaning the black background is considered as different shades of black, depending on the contrast size (0-255).

With regards to using different weapons, most exp farms uses sword as the tool for farming exp. That is why I mainly focused on using it as part of this script. But you are free to modify this script to add your idea, which is not bad, btw.

On my next update, I am planning on creating the script for afk wood farming, so the axe will definitely be used. But I may not finish it, since the laptop that I'm using is old, and the new Minecraft version 1.17 won't run on it. (I can only run Minecraft version 1.16.5 and below.)

**Comment by RaXorX** [comment]
That hurts to know, gladly I have a desktop too the laptop I had was too old to run 1.16.5 either (no opengl 4.0+ and in windows, even worse since the manufacturer dropped the support for it)

In regards to the full potential of the weapon. The Plus icon shows once the weapon has fully recharged and is targeting a mob/entity that's when it shows a + icon otherwise it'll simply show nothing if it isn't targetting anything. If I am not wrong that simply only is a visual thing and simply using the delay method I mentioned even for just the swords it would work the same. Say, setting the delay to 625+x (just to see the plus icon otherwise even setting at 625 it works fully) I had the same effect as doing an image search. And also, doesn't sweep effect works all the time? When there are multiple mobs when i use the sword it attacks them all. Basically the delay works as a substitute for searching the image instead.

**Comment by RaXorX** [comment]
@houdini101 I modified it to this. I can create a pull request if you want to. 
https://github.com/RaXorX/AHK_Minecraft_Tools/tree/gdip
